export const ALL_AUCTION_REQUEST = "ALL_AUCTION_REQUEST";
export const ALL_AUCTION_SUCCESS = "ALL_AUCTION_SUCCESS";
export const ALL_AUCTION_FAIL = "ALL_AUCTION_FAIL";

export const ADMIN_AUCTION_REQUEST = "ADMIN_AUCTION_REQUEST";
export const ADMIN_AUCTION_SUCCESS = "ADMIN_AUCTION_SUCCESS";
export const ADMIN_AUCTION_FAIL = "ADMIN_AUCTION_FAIL";

export const NEW_AUCTION_REQUEST = "NEW_AUCTION_REQUEST";
export const NEW_AUCTION_SUCCESS = "NEW_AUCTION_SUCCESS";
export const NEW_AUCTION_RESET = "NEW_AUCTION_RESET";
export const NEW_AUCTION_FAIL = "NEW_AUCTION_FAIL";

export const UPDATE_AUCTION_REQUEST = "UPDATE_AUCTION_REQUEST";
export const UPDATE_AUCTION_SUCCESS = "UPDATE_AUCTION_SUCCESS";
export const UPDATE_AUCTION_RESET = "UPDATE_AUCTION_RESET";
export const UPDATE_AUCTION_FAIL = "UPDATE_AUCTION_FAIL";

export const DELETE_AUCTION_REQUEST = "DELETE_AUCTION_REQUEST";
export const DELETE_AUCTION_SUCCESS = "DELETE_AUCTION_SUCCESS";
export const DELETE_AUCTION_RESET = "DELETE_AUCTION_RESET";
export const DELETE_AUCTION_FAIL = "DELETE_AUCTION_FAIL";

export const AUCTION_DETAILS_REQUEST = "AUCTION_DETAILS_REQUEST";
export const AUCTION_DETAILS_SUCCESS = "AUCTION_DETAILS_SUCCESS";
export const AUCTION_DETAILS_FAIL = "AUCTION_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

// auctionConstants.js

export const BID_REQUEST = "BID_REQUEST";
export const BID_SUCCESS = "BID_SUCCESS";
export const BID_FAIL = "BID_FAIL";
export const BID_RESET = "BID_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
